name = "tvbox-source"
main = "src/cf-entry.ts"
compatibility_date = "2024-12-30"
compatibility_flags = ["nodejs_compat"]

[triggers]
crons = ["0 * * * *"]

[[kv_namespaces]]
binding = "KV"
id = "2c00548a275a463fac0a944d824fd5e2"

[vars]
SPEED_TIMEOUT_MS = "5000"
SITE_TIMEOUT_MS = "3000"
FETCH_TIMEOUT_MS = "5000"
WORKER_BASE_URL = "https://tvbox.djsb.hidns.vip"
